### ISSUE TITLE
about branchs

### ISSUE THREAD

**Issue by SametAhmetSahin** [OmerAran/MovieApp#1]
Tahminim sebebinin GitHubda projenin ana branchi main iken yereldeki Gitte master brancha pushlanmış olması. Dolayısıyla readme ve gitignore main branchteyken proje dosyaları masterda. Merge request ve yereldeki gitte main branchına geçmek `git checkout main` sorunu çözer.

**Comment by OmerAran** [comment]
Thanks for the feedback, I got it.
